# Refs
# customizing the boot
#   - https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix

# Sudo enabled faz com que o travis inicialize
# uma máquina ubuntu full, caso contrário
# ele inicializa um docker.
# com a contrapartida de levar mais tempo no boot
# ref : https://docs.travis-ci.com/user/reference/overview/
sudo: enabled
dist: focal
arch: amd64

language: java
jdk:
  - oraclejdk8

# linguagens de desenvolvimento utilizada no build
language: python
python:
  - '3.6'
  
before_install:
   - sudo apt-get -qq update  
  
# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install build-essential
  - sudo apt-get install gcc make libxft2:i386 libxext6:i386 libncurses5:i386 libstdc++6:i386 libpng-dev libpng16-16:i386 libpng16-16 python-gobject libnotify-bin 
  
before_script:
# modelSim download
  - wget https://download.altera.com/akdlm/software/acdsinst/20.1std.1/720/ib_installers/ModelSimSetup-20.1.1.720-linux.run -O modelsim.run
# modelsim install
  - chmod +x modelsim.run
  - ./modelsim.run --mode unattended --accept_eula 1 --installdir $HOME
# corrigi bug modelsim com kernel 4
  - sed -i '209 a\        4.[0-9]*)             vco="linux" ;;' $HOME/modelsim_ase/vco 
# define o modelsim como simulador para o VUNIT
  - export VUNIT_SIMULATOR=modelsim
  - export VUNIT_MODELSIM_PATH=$HOME/modelsim_ase/bin/

##############################################
# INSERIR AQUI !!!
###############################################
script:
  ## Instal Z01.1 tools
  - bash updateZ01tools.sh 

  ## run scripts
  - python3 Projetos/A-AmbienteDesenvolvimento/testeAmbienteDesenvolvimento.py
